export class CreateUserDto {
    id:string;
    name: string;
	surname: string;
	surname_info:string;
	date_of_birth:string;
	citizenship:string;
	serial:string;
	number:string;
	PlaceOfIssue:string;
	date_of_issue:string;
	date_of_expiry:string;
	settlement_name:string;
	mobile_tel:string;
	email:string;
	edu_date_of_issue:string;
	edu_serial_number:string;
	edu_name:string;
	sex:string;
	country:string;
	DD:string;
	religion:string;
	DataYourPeople:string;
	NameSurname:string;
	PhoneRepresantative:string;
	country_pass:string;
	NatPassw:string;
	HostelLive:string;
	numberNational:string;
	pref_faculty:string;
}
